services:
  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    image: aus-project-jq-chat-service:latest
    container_name: chat-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: chat-container
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-https://api.openai.com/v1}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o}
    restart: unless-stopped

  chatbox-gui:
    build:
      context: ./chatbox-gui
      dockerfile: Dockerfile
    image: aus-project-jq-chatbox-gui:latest
    container_name: chatbox-gui
    environment:
      # reliable file watching on macOS/Windows
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      # RTK Query base URL
      - VITE_API_BASE=/api
    ports:
      - "3000:80"
    depends_on:
      - chat-service
    restart: unless-stopped