services:
  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    image: aus-project-jq-chat-service:latest
    container_name: chat-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: chat-container
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL:-https://api.openai.com/v1}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4o}
    restart: unless-stopped
